# Generated by Django 4.2.8 on 2023-12-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='entrenador_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('clima', models.CharField(max_length=255)),
                ('pueblo_inicial', models.CharField(max_length=255)),
                ('lider_liga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('habilidad', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemones', to='pokedex.region')),
            ],
        ),
    ]
