# Generated by Django 4.2.8 on 2023-12-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='clima',
        ),
        migrations.AddField(
            model_name='region',
            name='mapa',
            field=models.ImageField(blank=True, null=True, upload_to='region_maps/'),
        ),
    ]
